language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
          
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip 
  - pip3 install mysql-connector

  
script: python3 call_waiting.py || python call_waiting.py


