language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
          
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip 
  - pip3 install mysql-connector

env:
    flask=0.12.3

script: python3 call_waiting.py || python call_waiting.py


deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true


